version: '3.7'

services:
  crdb:
    container_name: cockroach-db
    hostname: crdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=security-cluster --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - micronaut_security_serverless_sample_network
  crdb-init:
    container_name: crdb-init
    hostname: crdb-init
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=crdb:26257
      - COCKROACH_INSECURE=true
      - DATABASE_NAME=security
    depends_on:
      - crdb
    networks:
      - micronaut_security_serverless_sample_network

networks:
  micronaut_security_serverless_sample_network:
    name: micronaut_security_serverless_sample_network
